name: Deployment Pipeline

on:
   workflow_run:
        workflows: ["Build and Test"] 
        types:
            - completed
   pull_request:
        types:
            - closed
   workflow_dispatch:
      inputs:
        production_approval:
            description: 'Approve Production Deployment'
            required: true
            default: 'false'    

env:    
      EB_PACKAGE_S3_BUCKET_NAME : "ebs-bucket-t1"
      EB_APPLICATION_NAME       : "Lunar"
      EB_ENVIRONMENT_NAME       : "Lunar-env"
      EB_version_label          : "EBS12AA"
           
jobs:
  deploy_staging:
        name: Deploy to Staging
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Deploy to Staging
          run:  echo "Deploying to Staging environment..."

        - name: Publish Artifacts
          run: dotnet publish -o package

        - name: Zip Artifacts 
          run: |
            cd package
            zip ../package.zip *

        - name: Configure AWS Credentials
          run: |
              aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws configure set region ${{ secrets.AWS_REGION_NAME }}
              
        - name: Copy Artifact to S3     
          run:  aws s3 cp package.zip s3://ebs-bucket-t1/package.zip
                  
        - name: Run Number
          run:  echo "${{github.run_number}}"
          
        - name: Deploy to EBS Staging 
          run: |
             aws elasticbeanstalk create-application-version --application-name ${{ env.EB_APPLICATION_NAME }}  --version-label "version@$(uuidgen | tr -d -)" --source-bundle S3Bucket=${{ env.EB_PACKAGE_S3_BUCKET_NAME }},S3Key=package.zip
             aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --application-name ${{ env.EB_APPLICATION_NAME }} 
             echo 'Deployment to AWS Elastic Beanstalk complete.'

  deploy_production:
        name: Deploy to Production (Manual Approval)
        runs-on: ubuntu-latest
        needs: [deploy_staging]
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.production_approval == 'true'

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Deploy Production
          run: echo "Deploying to production environment ..."
        
        - name: Publish Artifacts
          run: dotnet publish -o package

        - name: Zip Artifacts 
          run: |
            cd package
            zip ../package.zip *

        - name: Configure AWS Credentials
          run: |
              aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws configure set region ${{ secrets.AWS_REGION_NAME }}
              
        - name: Copy Artifact to S3     
          run:  aws s3 cp package.zip s3://ebs-bucket-t1/package.zip
                  
        - name: Run Number
          run:  echo "${{github.run_number}}"
          
        - name: Deploy to  Production Elastic Beanstalk
          run: |
             aws elasticbeanstalk create-application-version --application-name ${{ env.EB_APPLICATION_NAME }}  --version-label  "version@$(uuidgen | tr -d -)" --source-bundle S3Bucket=${{ env.EB_PACKAGE_S3_BUCKET_NAME }},S3Key=package.zip
             aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --application-name ${{ env.EB_APPLICATION_NAME }} 
             echo 'Deployment to production environment EBS'


